services:
  web:
    build:
      context: ../../../
      dockerfile: docker/dockerfiles/webserver/Dockerfile
    image: "maurinl/thetaboard:${TAG}"
    container_name: ${GUARDIANNAME}webserver
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - THETABOARD:/home/node/theta_mainnet
      - ../../../webserver/config:/home/node/app/webserver/config
      - /opt/assets:/home/node/app/modules/nifties/assets
    links:
      - maria:127.0.0.1
      - mongo:127.0.0.1
    networks:
      - backend
    depends_on:
      - maria
      - mongo
    environment:
      - NODE_PASSWORD=${NODE_PASSWORD}
      - API_TOKEN=${API_TOKEN}
      - PORT=${PORT}
      - NODE_ENV=${NODE_ENV}
      - DB=${DB}
      - MYSQL_PASS =${MYSQL_PASS}
  maria:
    image: "mariadb:10.5"
    restart: always
    container_name: ${GUARDIANNAME}mariadb
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASS}
      MYSQL_DATABASE: thetaboard
    command: mysqld --innodb-buffer-pool-size=10G --key_buffer_size=10M
    ports:
      - ${MYSQL_PORT}:3306
    networks:
      - backend
  mongo:
    image: mongo:5.0.6
    restart: always
    container_name: ${GUARDIANNAME}mongo
    volumes:
      - mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ${MYSQL_PASS}
    ports:
      - ${MONGO_PORT}:27017
    networks:
      - backend

volumes:
  THETABOARD:
    name: ${GUARDIANNAME}THETABOARD
  mysql:
    name: ${GUARDIANNAME}mysql
  mongo:
    name: ${GUARDIANNAME}mongo


networks:
  backend:
    name: ${GUARDIANNAME}backend
